### ISSUE TITLE
Can't get the traKmeter visible in Cubase 9.5 Windows 10 

### ISSUE THREAD

**Issue by Allmedialab** [mzuther/traKmeter#1]
Hi,
Thanks for the wonderful plugins. I got the K meter 64 .dll running in Cubase (but it get's black listed every time I startup Cubase) and unfortunately the traKmeter doesn't appear in Cubase. Also when I put the 64 bits .dll's of both plugins in the same folder Cubase can't find it. (res-scan in the plugin manager doesn't help either). In Reaper they both work without any problem!
Regards,
David

**Comment by mzuther** [comment]
Hi David!

I'm sorry to hear this, but I unfortunately do not have the time to help you with this. Maybe you could ask the Cubase support...

Martin

**Comment by Allmedialab** [comment]
Hi Martin,
No need to help me with this. I'm only reporting the issue this is Github! The K- meter VST 2 64 bits doesn't function proper in Cubase 9.5 latest updates, Windows 10 latest updates. The issue is that the meter only hits -24 when the level is clipping. The same audio in Reaper shows the proper lever. 
I'm sure it's not a Cubase support issue, I use Cubase since Atari days and have several meter plugins all working fine in Cubase. Would Validating the meter in Cubase change anything?
Regards,
David
