### ISSUE TITLE
Publish More Overview Stats 2.1 on GitHub

### ISSUE THREAD

**Issue by nicolasmaia** [mzuther/traKmeter#2]
Sorry to hijack this unrelated project, but it'd be nice if you could also upload your More Overview Stats 2.1 addon to GitHub. I'd like to report a bug.

**Comment by mzuther** [comment]
You're welcome!

However, I have stopped using the add-on myself and am not the author of "More Overview Stats 2.1". Maybe you can try the "Ask a question" button on the add-on's website?

Martin
