### ISSUE TITLE
Building the LV2 plugin on Linux fails

### ISSUE THREAD

**Issue by danielappelt** [mzuther/traKmeter#2]
I am trying to create an Arch Linux AUR package for your LV2 plugins. Following your documentation, I came up with this work-in-progress [build script](https://gist.github.com/danielappelt/c9841249e197a5b4ad6181e4af296421).

Unfortunately, building the x64 stereo plugin using 

`make config=release_x64 trakmeter_lv2_stereo`

fails. The compiler complains about two missing defines:

```
JucePlugin_MaxNumInputChannels
JucePlugin_MaxNumOutputChannels
```
I guess these definitions need to go into AppConfig.h? Defining them there (with a value of 2) seems to solve the problem.

Did I miss something in my build script, or is it something that needs to be taken care of during the configure/premake process?

**Comment by mzuther** [comment]
Hi Daniel,

thanks for trying to make an Arch package!

I have just updated to JUCE's new multichannel API.  And while stand-alone and VST of traKmeter seem to work, I still expect some glitches.

I hadn't checked the LV2 plug-in yet and have to confirm that it doesn't build.  I have already asked falkTX to update his DISTRHO LV2 implementation to the new API, but he currently has other priorities.  And he's probably right - this is already the second incarnation of the multichannel API within a few months...

I suggest using traKmeter v2.0.0 until I release the next official update.  It is working, and more than that, it's output has been thoroughly validated by me.  After all, what use is a meter that hasn't been checked?  There have been so many changes since v2.0.0 that there is the slight chance that the meter's readout may not be correct.  Or that the LV2 plug-in may not build at all... :)

**Comment by mzuther** [comment]
Setting the defines you mentioned is not a good idea, as they disable the multichannel API.  This could lead to some weird behaviour, something you as package maintainer want to avoid at all costs.  Unless you like cryptic bug reports. :)

**Comment by mzuther** [comment]
The LV2 plug-in compiles (and works) again.  Still, please do me a favour and use the latest stable version v2.0.0.

Note to self: I really should use a sensible version numbering... ;)

**Comment by danielappelt** [comment]
Hi Martin,

thanks for your feedback! I was maybe sold to Arch's way of always providing the latest stuff. So, it was a conscious decision to ignore the clearly visible official release and take the latest tagged version instead.

What you said makes perfect sense though! I will go for the latest released version now.

Unfortunately, I ran into another problem with this one, most probably due to the fact that Arch is using gcc6 by default. I get compilation errors comparable to falkTX/Carla#395. Do you think it would be sufficient to use

`
make CXXFLAGS=-DHAVE_LROUND config=release_x64 trakmeter_lv2_stereo
`

to solve this problem. Another option would be to require gcc5 for compilation.

PS: In my opinion, you don't have to change the way you apply version numbers. Software is never bug free. As a package maintainer it is always nice to have the ability to switch to a not-released, tagged version in order to provide a reproducable build in case there are problems with the last official release.

**Comment by mzuther** [comment]
I have just uploaded a new branch `gcc6-fix` which adds `-DHAVE_LROUND`. Please try if this works for you. It is based on the current `HEAD` (v2.3.0), but I was too lazy to install premake v4. :)

If this works, I can tell you how to change the premake file for v2.0.0 to fix the build...

Martin

**Comment by danielappelt** [comment]
Hey Martin,

I had problems applying your suggestions directly. So, I simply transferred your solution to a new branch based on v2.0.0. This seems to work just fine with premake4.
My proposition would be to merge the pull request into a [new, similarly named branch](https://help.github.com/articles/changing-the-base-branch-of-a-pull-request/).

**Comment by mzuther** [comment]
Done! :)

**Comment by danielappelt** [comment]
[trakmeter-lv2](https://aur.archlinux.org/packages/trakmeter-lv2/) is now available from the Arch User Repository.

**Comment by mzuther** [comment]
Great, thanks! :)

**Comment by danielappelt** [comment]
Hi Martin! I see you have deleted https://github.com/mzuther/traKmeter/tree/v2.0.0-gcc6 while there is no new official release. This renders the Arch User Repository package unusable for now.

Will there be a new release soon?

**Comment by mzuther** [comment]
Hi Daniel,

I have cleaned things up and fear that I have been overly fast.  Sorry 
for that!

Nevertheless, I am planning a new release for traKmeter.  This might 
take a few weeks, though, so it's probably better if I recreate 
v2.0.0-gcc6.  What you think?

Martin

**Comment by danielappelt** [comment]
Thank you, Martin!

**Comment by mzuther** [comment]
You're more than welcome! :)
