### ISSUE TITLE
Feature request: stable release version titles?

### ISSUE THREAD

**Issue by mxmilkiib** [mzuther/traKmeter#3]
Hello! I'd like to add traKmeter to https://libreav.org/updates but the more recent release titles have affected the ability to parse the [release feed](https://github.com/mzuther/traKmeter/releases.atom) entry titles, so I was wondering if I could request that the previous style gets used instead?

**Comment by mzuther** [comment]
Hi!

Thanks for considering to add traKmeter. However, I don't quite understand your request. The only change I'm aware is that I have started to annotate my GitHub releases with a description of the changes.

What exactly do you want me to change?

Thanks.

**Comment by mxmilkiib** [comment]
The title of the release annotation is the release version entry title in the feed; with a Firefox addon that prettifies feeds:
![image](https://user-images.githubusercontent.com/108225/104111347-b2233f00-52d8-11eb-8e29-906b2c2f6bc3.png)

If the version title could be of the "v2.4.1" or (something regular and easily parsable)?

**Comment by mzuther** [comment]
Got you! :smile:

Thanks for notifying me, I wasn't aware of this issue. I have now fixed this in all of my repositories.

For your info, not all items appearing in the release feed are actual releases. GitHub automatically adds some tagged commits to the feed. For example, I did not release v2.0.2 or v2.0.3.
