### ISSUE TITLE
Bug: UI is not working in VST2 version

### ISSUE THREAD

**Issue by starry-abyss** [mzuther/traKmeter#4]
### Describe the bug

I can run standalone, but in VST2 the UI is broken.

### Steps to reproduce

List *all* steps to reproduce the behavior:

1. move *.so of traKmeter VST2 plugin to ~/.vst
2. start Carla
3. press "Add Plugin" in Carla
4. double click on traKmeter (stereo) - it should be hosted now
5. go to "Rack" tab
6. right click on Carla-made UI of trakMeter
7. select "Show Custom UI"

### Expected behavior

I expect native traKmeter UI to be shown, just as in standalone version.

### Screenshots

This weird rectangle below in the middle is traKmeter VST2 UI:

![carla_trakmeter](https://user-images.githubusercontent.com/11571820/126087415-ee2fd4c3-24cf-4922-a312-764178c4e6bd.png)

### Environment (please complete the following information)

 - OS: openSUSE 15.3 64-bit
 - DAW: Carla 2.1.1 (in this issue I'm using it to connect JACK signals to traKmeter)
 - Plug-in: TraKmeter v2.4.7 VST 2 (64-bit)

Did you compile TraKmeter yourself? no

### Tool set (if you compiled the plug-in yourself)

Didn't compile

### Additional context

I also tried hosting it Renoise, and the UI is also completely broken there.

**Comment by mzuther** [comment]
Thanks for your bug report. I'm sorry for letting you wait, I was (and still am) pretty busy...

Can you download and try this build? It works on Carla 2.1.0 / Linux Mint 20.2 Cinnamon: [trakmeter-linux64-vst2_v2.4.7-99-ge191b55.tar.gz](https://public.mzuther.de/?b54552e5c59a6afd6cb5b142573efea1702ab260)

**Comment by starry-abyss** [comment]
Sorry, I forgot to test the newer build then, but I did now, and the UI works in Carla!

However, in Renoise it looks like this (the window doesn't draw its content):
![image](https://user-images.githubusercontent.com/11571820/137646886-8a2714e6-66ad-4725-8deb-8a92c2cbee1a.png)

**Comment by mzuther** [comment]
I am sorry, but I have to close this issue because I simply do not have enough time to support this project.
